LemmyNet/lemmy-translations

translators.json

I made a .json file with translators and their links (if they had). They are grouped by language.

Add translators.json

---

translations/en.json

This is for https://github.com/LemmyNet/lemmy-ui/issues/235#issue-850336480. I'm open for any suggestions to improve this message. I would also add a link to some explanation how federation works, but what we have in the docs is way too technical.
When merged, I would show this on the registration form only on lemmy.ml (I'm thinking some blue or green box with this text).

Add message for lemmy.ml registration

---

translations/en.json

figured i would help @soronixa out and make the PR.

Updating Account deletion prompt.

---

translations/en.json

For https://github.com/LemmyNet/lemmy-ui/pull/586

Add string default_theme

---

email/en.json

https://github.com/LemmyNet/lemmy/pull/2053

Add email translation

---

translations/en.json

See https://github.com/LemmyNet/lemmy/pull/2548

Add Tagline translations

---

translations/en.json

See https://github.com/LemmyNet/lemmy/pull/2585

Add Featured Post translations

---

translations/en.json

See https://github.com/LemmyNet/lemmy/pull/2616

Add custom emoji translations

---

translations/en.json

Custom emojis

---

translations/en.json

This goes along with the [UI PR](https://github.com/LemmyNet/lemmy-ui/pull/994).

Add modlog content warning translation

---

translations/en.json

https://github.com/LemmyNet/lemmy-ui/pull/1008

Add language_select_placeholder

---

translations/en.json

Another translation for the error page PR.

Error code translation

---

translations/en.json

Related to: https://github.com/LemmyNet/lemmy/pull/3074

Added error message for federation and private instance error

---

translations/en.json

In reference to https://github.com/LemmyNet/lemmy/pull/3074#discussion_r1229391347

merge federation private instance errors

---

translations/en.json

- Add `reset_password` string
- Related: https://github.com/LemmyNet/lemmy-ui/pull/1390

Add `reset_password` string

---

translations/en.json

Related: https://github.com/LemmyNet/lemmy-ui/pull/1623

Add acronym "OP" string

---

translations/en.json

Goes with: https://github.com/LemmyNet/lemmy/pull/3350

Add couldnt_create_audio_captcha

---

translations/en.json

Related to issue 282 of lemmy-ui

Add translation key for new setting 'Open links in new tab'

---

translations/en.json

This is for https://github.com/LemmyNet/lemmy-ui/pull/1675

Add message about uploaded image being too large

---

email/pt.json

URGENT: lemmy_server 'cargo build' is failing to compile due to this mistake. Fixes https://github.com/LemmyNet/lemmy-translations/issues/85

Update pt.json - fix lemmy_server compile failure

---

translations/en.json

Related: https://github.com/LemmyNet/lemmy-ui/pull/1870

Add value for default compact theme option

---

translations/en.json

Adds translations for [the corresponding UI PR](https://github.com/LemmyNet/lemmy-ui/pull/1861).

Add translations for show/hide password button

---

translations/en.json

Translations for [this UI PR](https://github.com/LemmyNet/lemmy-ui/pull/1875)

Add translations for remote follow

---

translations/en.json

These are error messages for my remote follow PR.

feat: Add translations for remote follow flow

---

translations/en.json

These are translations that will be needed for the UI for blocking instances.

feat: Add translations for blocking instances

---

translations/en.json

Related to [this UI PR](https://github.com/LemmyNet/lemmy-ui/issues/1015).

Add translations for language not allowed

---

translations/en.json

Adding regex info for block_urls.

---

translations/en.json

This will be used in lemmy-ui to help with magnet links.

Adding torrent help message.

---

translations/en.json

For the issue https://github.com/LemmyNet/lemmy-ui/issues/2743 and PR https://github.com/LemmyNet/lemmy-ui/pull/3030

Add banned from community badge string

---

translations/en.json

Same one used on join-lemmy.org now

Update donation text

---

translations/en.json

Moved these to untranslated in https://github.com/LemmyNet/lemmy/pull/6043.

Remove untranslated error
